name: "Obfuscate"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      - name: Start Obfuscating
        run: |
          cd obfuscate
          npm i
          npm install minify
          node obfuscate.js
          cd ..
          rm -rf obfuscate org .github .gitignore .git RSS.java Sitemap.java
      - name: Push to deployment Repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'mrepol742'
          destination-repository-name: 'mrepol742.github.io'
          user-email: mrepol742@gmail.com
          commit-message: Initial Commit
          target-branch: deployment